### ISSUE TITLE
Crashes when breaking paintings.

### ISSUE THREAD

**Issue by mineblock11** [WoMspace/Vector-Shader#3]
See title - occured on IRIS - 1.19.4

**Comment by mineblock11** [comment]
Tested and also occurs on Optifine

**Comment by WoMspace** [comment]
Cannot reproduce - what mods are you using?

**Comment by mineblock11** [comment]
Iris, Sodium, Fabric API 1.19.4

**Comment by WoMspace** [comment]
Are you using any other mods at all? And are the mods you're using the most recent releases?

**Comment by WoMspace** [comment]
cannot reproduce
